version: "3"

services:

    app:
      image: anamateska/kiii-project:latest
      build:
        context: .
        dockerfile: Dockerfile
      container_name: kiii-project
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/kiii-db
      ports:
        - 8080:8080
      depends_on:
        - db

    db:
      image: postgres
      container_name: kiii-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=anamateska
        - POSTGRES_DB=kiii-db
      ports:
        - 5432:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data

    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - 9000:9090
      volumes:
        - .\prometheus-conf\prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus-data:/prometheus

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - 3000:3000
      restart: unless-stopped
      volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana-data:/var/lib/grafana

volumes:
    postgres-data:
    prometheus-data:
    grafana-data:
