version: "3"
services:
    app:
      image: anamateska/kiii-project:latest
      build:
        context: .
        dockerfile: Dockerfile
      container_name: kiii-project
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/kiii-db
      ports:
        - 8080:8080
      depends_on:
        - db
    db:
      image: postgres
      container_name: kiii-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=anamateska
        - POSTGRES_DB=kiii-db
      ports:
        - 5432:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: